name: Build FEX-Emu DEB for ARM64 (Native ARM Runner)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04-arm # atau ubuntu-22.04-arm64
    steps:
      - name: Build inside Debian Sid container
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/output:/output \
            debian:sid-slim \
            bash -c "
              set -ex

              apt update
              apt install -y curl git cmake ninja-build build-essential clang lld \
                libasound2-dev libcapstone-dev libclang-19-dev libclang-21-dev \
                libcurl4-openssl-dev libdrm-dev libedit-dev libgl1-mesa-dev \
                libssl-dev libudev-dev libvulkan-dev libwayland-dev \
                libx11-dev libxcb1-dev libxcb-icccm4-dev libxcb-image0-dev \
                libxcb-keysyms1-dev libxcb-randr0-dev libxcb-render-util0-dev \
                libxcb-shape0-dev libxcb-shm0-dev libxcb-sync-dev \
                libxcb-xfixes0-dev libxcb-xinerama0-dev libxext-dev \
                libxrandr-dev libxxf86vm-dev libzstd-dev \
                llvm-19-dev nasm pkgconf python3 python3-pip python3-setuptools python3-venv \
                qml6-module-qtqml-workerscript qml6-module-qtquick-controls \
                qml6-module-qtquick-dialogs qml6-module-qtquick-layouts \
                qml6-module-qtquick-templates qml6-module-qtquick-window \
                qt6-base-dev qt6-declarative-dev squashfs-tools squashfuse \
                wayland-protocols

              git clone --recurse-submodules https://github.com/FEX-Emu/FEX.git /FEX
              cd /FEX
              mkdir build && cd build

              cmake .. -G Ninja \
                -DCMAKE_BUILD_TYPE=Release \
                -DCMAKE_C_COMPILER=clang \
                -DCMAKE_CXX_COMPILER=clang++ \
                -DUSE_LINKER=lld \
                -DENABLE_LTO=True \
                -DBUILD_TESTING=False \
                -DENABLE_ASSERTIONS=False \
                -DBUILD_THUNKS=True \
                -DCMAKE_INSTALL_PREFIX=/usr

              ninja -j\$(nproc)
              cpack -G DEB -C Release
              cp *.deb /output/
            "

      - name: Upload DEB artifact
        uses: actions/upload-artifact@v4
        with:
          name: fex-emu-deb
          path: output/*.deb
