name: Large Storage Cloudflare SSH

on:
  workflow_dispatch:

jobs:
  ssh-runner:
    runs-on: ubuntu-latest
    
    steps:
    - name: Free Up Disk Space
      run: |
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /usr/local/lib/android
        sudo rm -rf /opt/ghc
        sudo rm -rf "/usr/local/share/boost"
        df -h
        
    - name: Set up SSH Server
      run: |
        # Set password 'rahasia123' untuk user runner
        echo "runner:rahasia123" | sudo chpasswd
        sudo sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
        sudo systemctl restart ssh
        
    - name: Install & Run Cloudflare Tunnel
      run: |
        # Download Cloudflared resmi
        curl -L --output cloudflared.deb https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
        sudo dpkg -i cloudflared.deb
        
        echo "=========================================================="
        echo "TUNGGU BEBERAPA DETIK, LALU LIHAT LINK DI BAWAH INI!"
        echo "=========================================================="
        
        # Jalankan tunnel khusus SSH selama 6 jam
        cloudflared tunnel --url tcp://localhost:22 & sleep 21600
